export ZEXTRA_DIR="${ZEXTRA_DIR:=${HOME}/.zextra}"
# [[ -s "${ZEXTRA_DIR}/env.zsh" ]] && source "$ZEXTRA_DIR/env.zsh"
[[ -s "${ZEXTRA_DIR}/directories.zsh" ]] && source "$ZEXTRA_DIR/directories.zsh"

export TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'

unset zle_bracketed_paste

export BROWSER='open'
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
bindkey -v

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export KEYTIMEOUT=1

export GOPATH=${HOME}/golang
export GOROOT=/usr/local/opt/go/libexec
export JBOSS_HOME=/usr/local/opt/jboss-as/libexec
export GROOVY_HOME=/usr/local/opt/groovy/libexec
export ECLIPSE_HOME="${HOME}/Applications/Eclipse.app/Contents/Eclipse"
export ANDROID_HOME=$HOME/projects/android/sdk
export USE_CCACHE=1

# [[ -d /Applications/Xcode-beta.app ]] && export PATH="/Applications/Xcode-beta.app/Contents/Developer/usr/bin:${PATH}"

typeset -gU cdpath fpath mailpath path
cdpath=(
  ${HOME}/projects
  $cdpath
)

path=(
  ${HOME}/bin
  /usr/local/{bin,sbin,heroku/bin}
  /Applications/Postgres.app/Contents/Versions/9.5/bin
  /Applications/Xcode.app/Contents/Developer/usr/bin
  $path
  ${JBOSS_HOME}/bin
  ${HOME}/Library/Developer
  ${GOPATH}/bin
  ${GOROOT}/bin
)

fpath=(
  ${HOME}/.zextra/completions
  ${HOME}/.zextra/functions
  $fpath
)
autoload gi man mount-android unmount-android name-dir pygless rails take

[[ -x /usr/libexec/java_home ]] && export JAVA_HOME="$(/usr/libexec/java_home)"
[[ -f "${HOME}/.env" ]] && source "${HOME}/.env"

export LESS='-F -g -i -M -R -S -w -X -z-4'

if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#  vim: set ts=8 sw=2 tw=0 ft=zsh et :
