export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="morgan"

plugins=(git brew bower bundler compleat lol osx rails rake-fast ruby rvm tmux tmuxinator zeus)

bindkey -v

# export MANPATH="/usr/local/man:$MANPATH"
export POWERLINE_CONFIG_COMMAND=/Users/morgan/.vim/bundle/powerline/scripts/powerline-config
export HOMEBREW_GITHUB_API_TOKEN=22a666338b8aa4ce66c3ceb0f2151c7233f8acd4

source $ZSH/oh-my-zsh.sh
source ~/bin/tmuxinator.zsh
source ~/.nvm/nvm.sh
source $ZEXTRA_DIR/aliases.zsh
source $ZSH_CUSTOM/directories.zsh
source $ZSH_CUSTOM/functions.zsh

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export KEYTIMEOUT=1

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
