if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
else
  echo "SHIT HAPPENED!"
fi

[[ -s "$ZEXTRA_DIR/aliases.zsh" ]] && source "${ZEXTRA_DIR}/aliases.zsh"
[[ -s "${ZEXTRA_DIR}/directories.zsh" ]] && source "${ZEXTRA_DIR}/directories.zsh"
export RANGER_LOAD_DEFAULT_RC=false

[[ -f "${ZEXTRA_DIR}/zsh-autoenv/autoenv.zsh" ]] && source "${ZEXTRA_DIR}/zsh-autoenv/autoenv.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
