hash -d go="/Users/morgan/golang"
hash -d android="/Users/morgan/projects/android"
hash -d projects="/Users/morgan/projects"
hash -d ruby="/Users/morgan/projects/ruby"
hash -d dotfiles="/Users/morgan/projects/dotfiles"
hash -d morgflix="/Users/morgan/projects/morgflix"
hash -d httparty_cooler="/Users/morgan/projects/ruby/httparty-cooler"
hash -d chef-repo="/Users/morgan/chef-repo"
hash -d dash_docsets="/Users/morgan/Documents/documentation/dash_docsets"
hash -d chef-helpers="/Users/morgan/projects/ruby/chef_helpers"

hash -d clink="/Users/morgan/projects/c_family/corsair/corsair_link"
hash -d av_utils="/Users/morgan/projects/ruby/av_utils"
hash -d devpgk="/Users/morgan/projects/c_family/c_the_hard_way/devpkg"
hash -d tensorflow="/Users/morgan/projects/python/tensorflow"

hash -d lcthw="/Users/morgan/projects/c_family/c_the_hard_way/lcthw"
hash -d python="/Users/morgan/projects/python"
hash -d twits="/Users/morgan/projects/ruby/twits"
hash -d coach="/Users/morgan/projects/coach"
hash -d ng-gen="/Users/morgan/projects/ng_generate"
hash -d ts-osa="/Users/morgan/projects/javascript/ts_osa"
hash -d RubyKit="/Users/morgan/projects/apple/RubyKit"
hash -d TrumpScript="/Users/morgan/projects/llvm/TrumpScript"
