hash -d go="/Users/morgan/golang"
hash -d android="/Volumes/SSD2/projects/android"
hash -d projects="/Volumes/SSD2/projects"
hash -d ruby="/Volumes/SSD2/projects/ruby"
hash -d dotfiles="/Volumes/SSD2/projects/dotfiles"
hash -d morgflix="/Volumes/SSD2/projects/morgflix"
hash -d httparty_cooler="/Volumes/SSD2/projects/ruby/httparty-cooler"
hash -d chef-repo="/Users/morgan/chef-repo"
hash -d dash_docsets="/Users/morgan/Documents/documentation/dash_docsets"
hash -d chef-helpers="/Volumes/SSD2/projects/ruby/chef_helpers"

hash -d clink="/Volumes/SSD2/projects/c_family/corsair/corsair_link"
hash -d av_utils="/Volumes/SSD2/projects/ruby/av_utils"
hash -d devpgk="/Volumes/SSD2/projects/c_family/c_the_hard_way/devpkg"
hash -d tensorflow="/Volumes/SSD2/projects/python/tensorflow"

hash -d lcthw="/Volumes/SSD2/projects/c_family/c_the_hard_way/lcthw"
hash -d python="/Volumes/SSD2/projects/python"
hash -d twits="/Volumes/SSD2/projects/ruby/twits"
hash -d coach="/Volumes/SSD2/projects/coach"
hash -d ng-gen="/Volumes/SSD2/projects/ng_generate"
hash -d ts-osa="/Volumes/SSD2/projects/javascript/ts_osa"
hash -d RubyKit="/Volumes/SSD2/projects/apple/RubyKit"
hash -d TrumpScript="/Volumes/SSD2/projects/llvm/TrumpScript"
